"""F-14: PDF report generation using WeasyPrint + Jinja2."""

from __future__ import annotations

import logging
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any
from uuid import UUID

from jinja2 import Environment, FileSystemLoader
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.threat import Threat
from app.models.threat_model import ThreatModel
from app.schemas.environment_evidence import (
    CloudScanEvidence,
    IacEvidence,
    RepositoryEvidence,
)
from app.schemas.report import VALID_SECTION_IDS, ReportTemplateDefinition
from app.schemas.threat import ThreatResponse
from app.schemas.threat_model import ThreatModelAssumptionResponse
from app.services.compliance_service import lookup_controls_batch
from app.services.model_governance import normalize_control_library
from app.services.report_templates import get_report_template
from app.services.residual_risk import (
    build_residual_risk_summary,
    derive_residual_risk_level,
    normalize_control_effectiveness,
)

logger = logging.getLogger(__name__)

TEMPLATE_DIR = Path(__file__).resolve().parent.parent / "templates"
STRUCTURED_TEMPLATE_FILE = "report_structured.html"
REPORTABLE_STATUSES = ("Open", "In Progress", "Mitigated", "Accepted")

METHODOLOGY_TEXT = (
    "This threat model was generated by ThreatGenix using the STRIDE methodology "
    "(Spoofing, Tampering, Repudiation, Information Disclosure, Denial of Service, "
    "Elevation of Privilege). Threats were identified through a two-layer approach: "
    "(1) a deterministic rules engine comprising 41 STRIDE rules applied to the system's "
    "Data Flow Diagram, producing consistent and auditable findings independent of AI; "
    "(2) AI-powered contextual enhancement via AWS Bedrock (ca-central-1 region), which "
    "enriches threat descriptions with system-specific context and adds novel threats not "
    "covered by the rules engine. AI enhancement is optional — if unavailable, the rules-only "
    "output is used. Compliance mappings reference NIST 800-53, OSFI B-13, PCI DSS 4.0, "
    "and ISO 27001 controls (328 seeded control mappings). Threat intelligence enrichment "
    "draws from MITRE ATT&CK, CAPEC, CWE, CISA KEV, CCCS advisories, and CRI Profile "
    "for the financial sector. All AI inference is performed within ca-central-1; "
    "no customer data is used for model training. "
    "This threat model satisfies the threat modeling requirement under OSFI B-13 Section 3.1.6 "
    "(Technology and Cyber Risk Management), which requires federally regulated financial "
    "institutions to conduct threat modeling as part of their technology risk management program. "
    "Residual risk levels are derived from a 4-level severity x control-effectiveness matrix "
    "(adapted from ISO 27005 Annex E). When control effectiveness has not been explicitly recorded "
    "by an analyst, residual risk defaults to the inherent severity level (conservative assumption). "
    "This report should be reviewed by a qualified security professional before being entered "
    "into the organization's risk register."
)


_CITATION_RE = re.compile(
    r"(?:T\d{4}(?:\.\d{3})?|CAPEC-\d+|CWE-\d+)"
)


def _extract_citations(description: str, db_citations: list[Any] | None) -> list[str]:
    """Extract ATT&CK/CAPEC/CWE citation IDs from description text and DB column."""
    found: list[str] = []
    # From description text inline references
    found.extend(_CITATION_RE.findall(description))
    # From DB citations column (list of dicts with 'id' key, or plain strings)
    for item in db_citations or []:
        if isinstance(item, str):
            found.extend(_CITATION_RE.findall(item))
        elif isinstance(item, dict) and "id" in item:
            found.extend(_CITATION_RE.findall(str(item["id"])))
    # Deduplicate while preserving order
    seen: set[str] = set()
    result: list[str] = []
    for cid in found:
        if cid not in seen:
            seen.add(cid)
            result.append(cid)
    return result


def _derive_mitigation_status(threat: ThreatResponse) -> str:
    if threat.status in ("In Progress", "Mitigated"):
        return threat.status
    if (
        threat.mitigation_plan
        or threat.mitigation_owner
        or threat.due_date is not None
        or threat.mitigation_notes
    ):
        return "Planned"
    return ""


def _truncate_list(values: list[str], *, limit: int = 8) -> list[str]:
    return [value for value in values if value][:limit]


def _normalize_assumptions(raw_assumptions: list[dict[str, Any]] | None) -> list[ThreatModelAssumptionResponse]:
    normalized: list[ThreatModelAssumptionResponse] = []
    for item in raw_assumptions or []:
        try:
            normalized.append(ThreatModelAssumptionResponse.model_validate(item))
        except Exception:
            continue
    return sorted(normalized, key=lambda item: item.updated_at, reverse=True)


def _load_repository_evidence(raw: dict[str, Any] | None) -> RepositoryEvidence | None:
    if not raw:
        return None
    try:
        return RepositoryEvidence.model_validate(raw)
    except Exception:
        return None


def _load_cloud_evidence(raw: dict[str, Any] | None) -> CloudScanEvidence | None:
    if not raw:
        return None
    try:
        return CloudScanEvidence.model_validate(raw)
    except Exception:
        return None


def _load_iac_evidence(raw: dict[str, Any] | None) -> IacEvidence | None:
    if not raw:
        return None
    try:
        return IacEvidence.model_validate(raw)
    except Exception:
        return None


def _build_system_context(threat_model: ThreatModel) -> dict[str, Any]:
    repository = _load_repository_evidence(getattr(threat_model, "repository_evidence", None))
    cloud = _load_cloud_evidence(getattr(threat_model, "cloud_scan_evidence", None))
    iac = _load_iac_evidence(getattr(threat_model, "iac_evidence", None))

    return {
        "deployment_model": getattr(threat_model, "deployment_model", None) or "Not specified",
        "regulatory_scope": list(getattr(threat_model, "regulatory_scope", None) or []),
        "environment_context_summary": getattr(threat_model, "environment_context_summary", None) or "",
        "languages": _truncate_list(list(repository.languages) if repository else []),
        "frameworks": _truncate_list(list(repository.frameworks) if repository else []),
        "entrypoints": _truncate_list(list(repository.entrypoints) if repository else []),
        "api_routes": _truncate_list(list(repository.api_routes) if repository else []),
        "auth_mechanisms": _truncate_list(list(repository.auth_mechanisms) if repository else []),
        "data_stores": _truncate_list(list(repository.data_stores) if repository else []),
        "queues": _truncate_list(list(repository.queues) if repository else []),
        "external_integrations": _truncate_list(list(repository.external_integrations) if repository else []),
        "deployment_clues": _truncate_list(list(repository.deployment_clues) if repository else []),
        "infrastructure_resources": _truncate_list(list(repository.infrastructure_resources) if repository else []),
        "exposed_services": _truncate_list(list(cloud.exposed_services) if cloud else []),
        "identity_risks": _truncate_list(list(cloud.identity_risks) if cloud else []),
        "encryption_gaps": _truncate_list(list(cloud.encryption_gaps) if cloud else []),
        "public_exposure": _truncate_list(list(iac.public_exposure) if iac else []),
        "iam_bindings": _truncate_list(list(iac.iam_bindings) if iac else []),
        "network_paths": _truncate_list(list(iac.network_paths) if iac else []),
        "secret_refs": _truncate_list(list(iac.secret_refs) if iac else []),
        "warnings": _truncate_list(
            [
                *(list(repository.warnings) if repository else []),
                *(list(cloud.warnings) if cloud else []),
                *(list(iac.warnings) if iac else []),
            ],
            limit=12,
        ),
    }


def _build_render_sections(
    *,
    template_definition: ReportTemplateDefinition,
    enabled_sections: set[str] | None,
    system_name: str,
    description: str,
    data_classification: str,
    created_at: str,
    generated_at: str,
    dfd_image_base64: str,
    dfd_integrity_sha256: str,
    arch_diagrams: list[dict[str, Any]],
    threat_dicts: list[dict[str, Any]],
    critical_high_threats: list[dict[str, Any]],
    critical_high_count: int,
    open_count: int,
    accepted_count: int,
    residual_risk_summary: dict[str, int],
    compliance_by_threat: list[dict[str, Any]],
    scan_summary: dict[str, Any],
    scan_threat_results: list[dict[str, Any]],
    validation_runbook: dict[str, Any] | None,
    responsibility_matrix: dict[str, Any],
    controls: list[dict[str, Any]],
    assumptions: list[dict[str, Any]],
    system_context: dict[str, Any],
    analyst_name: str = "",
    analyst_attestation: str = "",
    next_review_date: str = "",
    out_of_scope_statement: str = "",
) -> list[dict[str, Any]]:
    sections_to_render: list[dict[str, Any]] = []
    for entry in template_definition.sections:
        if entry.kind == "built_in":
            source_section_id = entry.source_section_id or entry.id
            if enabled_sections is not None and source_section_id not in enabled_sections:
                continue

            if source_section_id == "executive_summary":
                accepted_threats = [
                    item for item in threat_dicts if item["status"] == "Accepted"
                ]
                sections_to_render.append(
                    {
                        "kind": "executive_summary",
                        "title": entry.title,
                        "intro_text": entry.intro_text,
                        "critical_high_count": critical_high_count,
                        "total_threats": len(threat_dicts),
                        "open_count": open_count,
                        "accepted_count": accepted_count,
                        "accepted_threats": accepted_threats,
                        "critical_high_threats": critical_high_threats[:10],
                        "residual_risk_summary": residual_risk_summary,
                    }
                )
            elif source_section_id == "scope":
                scope_items: list[tuple[str, str]] = [
                    ("System Name", system_name),
                    ("Description", description or "No description provided."),
                    ("Data Classification", data_classification),
                    ("Created", created_at),
                    ("Generated", generated_at),
                ]
                if next_review_date:
                    scope_items.append(("Next Review Date", next_review_date))
                if out_of_scope_statement:
                    scope_items.append(("Out of Scope", out_of_scope_statement))
                sections_to_render.append(
                    {
                        "kind": "scope",
                        "title": entry.title,
                        "intro_text": entry.intro_text,
                        "items": scope_items,
                    }
                )
            elif source_section_id == "system_context":
                sections_to_render.append(
                    {
                        "kind": "system_context",
                        "title": entry.title,
                        "intro_text": entry.intro_text,
                        "context": system_context,
                    }
                )
            elif source_section_id == "dfd":
                sections_to_render.append(
                    {
                        "kind": "dfd",
                        "title": entry.title,
                        "intro_text": entry.intro_text,
                        "dfd_image_base64": dfd_image_base64,
                        "dfd_integrity_sha256": dfd_integrity_sha256,
                    }
                )
            elif source_section_id == "arch_diagrams":
                sections_to_render.append(
                    {
                        "kind": "arch_diagrams",
                        "title": entry.title,
                        "intro_text": entry.intro_text,
                        "arch_diagrams": arch_diagrams,
                    }
                )
            elif source_section_id == "threats":
                sections_to_render.append(
                    {
                        "kind": "threats",
                        "title": entry.title,
                        "intro_text": entry.intro_text,
                        "threats": threat_dicts,
                    }
                )
            elif source_section_id == "controls":
                sections_to_render.append(
                    {
                        "kind": "controls",
                        "title": entry.title,
                        "intro_text": entry.intro_text,
                        "controls": controls,
                    }
                )
            elif source_section_id == "assumptions":
                sections_to_render.append(
                    {
                        "kind": "assumptions",
                        "title": entry.title,
                        "intro_text": entry.intro_text,
                        "assumptions": assumptions,
                    }
                )
            elif source_section_id == "compliance":
                sections_to_render.append(
                    {
                        "kind": "compliance",
                        "title": entry.title,
                        "intro_text": entry.intro_text,
                        "compliance_by_threat": compliance_by_threat,
                    }
                )
            elif source_section_id == "scan_validation":
                sections_to_render.append(
                    {
                        "kind": "scan_validation",
                        "title": entry.title,
                        "intro_text": entry.intro_text,
                        "scan_summary": scan_summary,
                        "scan_threat_results": scan_threat_results,
                        "validation_runbook": validation_runbook,
                    }
                )
            elif source_section_id == "responsibility_matrix":
                sections_to_render.append(
                    {
                        "kind": "responsibility_matrix",
                        "title": entry.title,
                        "intro_text": entry.intro_text,
                        "responsibility_matrix": responsibility_matrix,
                    }
                )
            elif source_section_id == "methodology":
                sections_to_render.append(
                    {
                        "kind": "methodology",
                        "title": entry.title,
                        "intro_text": entry.intro_text,
                        "methodology_text": METHODOLOGY_TEXT,
                    }
                )
            elif source_section_id == "attestation":
                sections_to_render.append(
                    {
                        "kind": "attestation",
                        "title": entry.title,
                        "intro_text": entry.intro_text,
                        "analyst_name": analyst_name,
                        "analyst_attestation": analyst_attestation,
                        "next_review_date": next_review_date,
                        "generated_at": generated_at,
                    }
                )
            elif source_section_id == "threat_intel_refs":
                # Threats that have at least one ATT&CK/CAPEC/CWE citation
                intel_entries = [
                    {
                        "display_id": t["display_id"],
                        "stride_category": t["stride_category"],
                        "severity": t["severity"],
                        "citations": t.get("citations") or [],
                    }
                    for t in threat_dicts
                    if t.get("citations")
                ]
                sections_to_render.append(
                    {
                        "kind": "threat_intel_refs",
                        "title": entry.title or "Threat Intelligence References",
                        "intro_text": entry.intro_text,
                        "entries": intel_entries,
                    }
                )
            continue

        sections_to_render.append(
            {
                "kind": "custom_text",
                "title": entry.title,
                "intro_text": entry.intro_text,
                "body": entry.body or "",
            }
        )

    for index, section in enumerate(sections_to_render, start=1):
        section["number"] = index
    return sections_to_render


async def generate_report(
    db: AsyncSession,
    threat_model_id: UUID,
    dfd_image_base64: str = "",
    dfd_integrity_sha256: str = "",
    sections: list[str] | None = None,
) -> bytes:
    """Load threat model data, render HTML via Jinja2, convert to PDF via WeasyPrint."""
    result = await db.execute(select(ThreatModel).where(ThreatModel.id == threat_model_id))
    threat_model = result.scalar_one_or_none()
    if threat_model is None:
        raise ValueError(f"Threat model {threat_model_id} not found")

    template_definition = get_report_template(
        getattr(threat_model, "report_templates", None),
        getattr(threat_model, "report_template", None),
    )

    threats_result = await db.execute(
        select(Threat)
        .where(
            Threat.threat_model_id == threat_model_id,
            Threat.status.in_(REPORTABLE_STATUSES),
        )
        .order_by(Threat.display_id)
    )
    threats = list(threats_result.scalars().all())

    controls_map = await lookup_controls_batch(db, threats)

    from app.models.scan import ScanJob, ScanThreatResult
    from app.services.validation_runbook import build_validation_runbook

    scan_result = await db.execute(
        select(ScanJob)
        .where(
            ScanJob.threat_model_id == threat_model_id,
            ScanJob.status == "completed",
        )
        .order_by(ScanJob.created_at.desc())
        .limit(1)
    )
    latest_scan = scan_result.scalar_one_or_none()

    scan_threat_results: list[dict[str, Any]] = []
    validation_runbook: dict[str, Any] | None = None
    scan_summary: dict[str, Any] = {
        "has_scan": False,
        "scan_date": None,
        "finding_count": 0,
        "confirmed_count": 0,
        "mitigated_count": 0,
        "not_found_count": 0,
        "unverifiable_count": 0,
    }

    threat_scan_map: dict[str, Any] = {}
    if latest_scan:
        tr_result = await db.execute(
            select(ScanThreatResult).where(ScanThreatResult.scan_job_id == latest_scan.id)
        )
        threat_scan_rows = list(tr_result.scalars().all())
        threat_scan_map = {str(item.threat_id): item for item in threat_scan_rows}
        scan_summary = {
            "has_scan": True,
            "scan_date": latest_scan.completed_at.strftime("%Y-%m-%d %H:%M UTC")
            if latest_scan.completed_at
            else "N/A",
            "finding_count": latest_scan.finding_count,
            "confirmed_count": sum(1 for item in threat_scan_rows if item.scan_status == "confirmed"),
            "mitigated_count": sum(1 for item in threat_scan_rows if item.scan_status == "mitigated"),
            "not_found_count": sum(1 for item in threat_scan_rows if item.scan_status == "not_found"),
            "unverifiable_count": sum(1 for item in threat_scan_rows if item.scan_status == "unverifiable"),
        }
        runbook = await build_validation_runbook(db, latest_scan.id)
        validation_runbook = runbook.model_dump(mode="json") if runbook is not None else None

    threat_dicts: list[dict[str, Any]] = []
    compliance_by_threat: list[dict[str, Any]] = []
    for threat in threats:
        response = ThreatResponse.model_validate(threat)
        response.compliance_controls = controls_map.get(threat.id, [])
        _desc = response.description or ""
        _desc_pdf = _desc[:2000] + " …" if len(_desc) > 2000 else _desc
        threat_dict = {
            "display_id": response.display_id,
            "stride_category": response.stride_category,
            "severity": response.severity,
            "description": _desc_pdf,
            "source": response.source,
            "status": response.status,
            "relevance_rationale": response.relevance_rationale or "",
            "rule_id": response.rule_id or "",
            "threat_subtype": response.threat_subtype or "",
            "ai_enhanced": response.ai_enhanced,
            "mitigation_plan": response.mitigation_plan or "",
            "mitigation_owner": response.mitigation_owner or "",
            "mitigation_due_date": response.due_date.isoformat() if response.due_date else "",
            "mitigation_status": _derive_mitigation_status(response),
            "control_effectiveness": normalize_control_effectiveness(response.control_effectiveness),
            "residual_risk_level": response.residual_risk_level
            or derive_residual_risk_level(response.severity, response.control_effectiveness),
            "provider_managed": response.provider_managed,
            "citations": _extract_citations(
                response.description, getattr(threat, "citations", None)
            ),
        }
        threat_dicts.append(threat_dict)
        compliance_by_threat.append(
            {
                "display_id": response.display_id,
                "stride_category": response.stride_category,
                "controls": [
                    {
                        "control_id": control.control_id,
                        "control_name": control.control_name,
                        "framework": control.framework,
                    }
                    for control in response.compliance_controls
                ],
            }
        )
        if latest_scan:
            scan_result_row = threat_scan_map.get(str(threat.id))
            scan_threat_results.append(
                {
                    **threat_dict,
                    "scan_status": scan_result_row.scan_status if scan_result_row else "unverifiable",
                    "cve_ids": scan_result_row.cve_ids if scan_result_row else [],
                }
            )

    critical_high_threats = [
        item for item in threat_dicts if item["severity"] in ("Critical", "High")
    ]
    critical_high_count = len(critical_high_threats)
    open_count = sum(1 for item in threat_dicts if item["status"] == "Open")
    accepted_count = sum(1 for item in threat_dicts if item["status"] == "Accepted")
    residual_risk_summary = build_residual_risk_summary(
        [item["residual_risk_level"] for item in threat_dicts]
    )

    provider_threats = [item for item in threat_dicts if item["provider_managed"]]
    customer_threats = [item for item in threat_dicts if not item["provider_managed"]]
    responsibility_matrix = {
        "provider": provider_threats,
        "customer": customer_threats,
        "has_cloud_threats": bool(provider_threats),
    }

    controls = [
        {
            "title": item.title,
            "description": item.description,
            "category": item.category,
            "status": item.status,
            "owner": item.owner,
            "evidence": item.evidence,
            "mapped_threat_count": len(item.mapped_threat_ids),
            "updated_at": item.updated_at.strftime("%Y-%m-%d %H:%M UTC"),
        }
        for item in normalize_control_library(getattr(threat_model, "control_library", None))
    ]
    assumptions = [
        {
            "title": item.title,
            "description": item.description,
            "status": item.status,
            "anchor_label": item.anchor_label,
            "updated_at": item.updated_at.strftime("%Y-%m-%d %H:%M UTC"),
        }
        for item in _normalize_assumptions(getattr(threat_model, "assumptions", None))
    ]
    system_context = _build_system_context(threat_model)

    enabled_sections = None
    if sections:
        enabled_sections = {section_id for section_id in sections if section_id in VALID_SECTION_IDS}

    now = datetime.now(timezone.utc)
    render_sections = _build_render_sections(
        template_definition=template_definition,
        enabled_sections=enabled_sections,
        system_name=threat_model.system_name,
        description=threat_model.description,
        data_classification=threat_model.data_classification,
        created_at=threat_model.created_at.strftime("%Y-%m-%d %H:%M UTC")
        if threat_model.created_at
        else "N/A",
        generated_at=now.strftime("%Y-%m-%d %H:%M UTC"),
        dfd_image_base64=dfd_image_base64,
        dfd_integrity_sha256=dfd_integrity_sha256,
        arch_diagrams=list(getattr(threat_model, "arch_diagrams", None) or []),
        threat_dicts=threat_dicts,
        critical_high_threats=critical_high_threats,
        critical_high_count=critical_high_count,
        open_count=open_count,
        accepted_count=accepted_count,
        residual_risk_summary=residual_risk_summary,
        compliance_by_threat=compliance_by_threat,
        scan_summary=scan_summary,
        scan_threat_results=scan_threat_results,
        validation_runbook=validation_runbook,
        responsibility_matrix=responsibility_matrix,
        controls=controls,
        assumptions=assumptions,
        system_context=system_context,
        analyst_name=getattr(threat_model, "analyst_name", None) or "",
        analyst_attestation=getattr(threat_model, "analyst_attestation", None) or "",
        next_review_date=str(getattr(threat_model, "next_review_date", None) or ""),
        out_of_scope_statement=getattr(threat_model, "out_of_scope_statement", None) or "",
    )

    context = {
        "system_name": threat_model.system_name,
        "description": threat_model.description,
        "data_classification": threat_model.data_classification,
        "created_at": threat_model.created_at.strftime("%Y-%m-%d %H:%M UTC")
        if threat_model.created_at
        else "N/A",
        "generated_at": now.strftime("%Y-%m-%d %H:%M UTC"),
        "cover_title": template_definition.cover_title,
        "cover_subtitle": template_definition.cover_subtitle,
        "template_label": template_definition.name,
        "template_description": template_definition.description,
        "template_audience": template_definition.audience,
        "report_logo_base64": getattr(threat_model, "report_logo_base64", "") or "",
        "report_watermark_text": getattr(threat_model, "report_watermark_text", "") or "",
        "analyst_name": getattr(threat_model, "analyst_name", None) or "",
        "analyst_attestation": getattr(threat_model, "analyst_attestation", None) or "",
        "next_review_date": str(getattr(threat_model, "next_review_date", None) or ""),
        "out_of_scope_statement": getattr(threat_model, "out_of_scope_statement", None) or "",
        "render_sections": render_sections,
        "app_version": "0.1.0",
    }

    # autoescape=True: WeasyPrint parses HTML, so entities like &lt; render correctly as < in the PDF.
    # autoescape protects against malformed HTML from user-supplied threat descriptions.
    env = Environment(loader=FileSystemLoader(str(TEMPLATE_DIR)), autoescape=True)
    template = env.get_template(STRUCTURED_TEMPLATE_FILE)
    html_content = template.render(**context)

    from weasyprint import HTML

    pdf_bytes = HTML(string=html_content).write_pdf()
    logger.info(
        "pdf_report_generated threat_model_id=%s template=%s threats=%d size_bytes=%d",
        threat_model_id,
        template_definition.id,
        len(threats),
        len(pdf_bytes),
    )
    return pdf_bytes
